CREATE TABLE clinical_notes (
    id VARCHAR(36) PRIMARY KEY,
    hospital_id VARCHAR(36) NOT NULL,
    patient_id VARCHAR(36) NOT NULL,
    patient_round_review_id VARCHAR(36),
    author_id VARCHAR(36) NOT NULL,
    note_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    is_amended TINYINT(1) NOT NULL DEFAULT 0,
    amended_by_id VARCHAR(36),
    amended_at DATETIME,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_note_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    CONSTRAINT fk_note_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_note_review FOREIGN KEY (patient_round_review_id) REFERENCES patient_round_reviews(id),
    CONSTRAINT fk_note_author FOREIGN KEY (author_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE care_tasks (
    id VARCHAR(36) PRIMARY KEY,
    hospital_id VARCHAR(36) NOT NULL,
    patient_id VARCHAR(36) NOT NULL,
    ward_id VARCHAR(36) NOT NULL,
    round_id VARCHAR(36),
    created_by_id VARCHAR(36) NOT NULL,
    assigned_to_id VARCHAR(36),
    assigned_to_role VARCHAR(50),
    task_type VARCHAR(255) NOT NULL,
    source VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    priority VARCHAR(50) NOT NULL DEFAULT 'ROUTINE',
    window_start DATETIME,
    window_end DATETIME,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    completed_by_id VARCHAR(36),
    completed_at DATETIME,
    escalated_at DATETIME,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_task_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    CONSTRAINT fk_task_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_task_ward FOREIGN KEY (ward_id) REFERENCES wards(id),
    CONSTRAINT fk_task_round FOREIGN KEY (round_id) REFERENCES rounds(id),
    CONSTRAINT fk_task_creator FOREIGN KEY (created_by_id) REFERENCES users(id),
    CONSTRAINT fk_task_assignee FOREIGN KEY (assigned_to_id) REFERENCES users(id),
    CONSTRAINT fk_task_completor FOREIGN KEY (completed_by_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
