CREATE TABLE patients (
    id VARCHAR(36) PRIMARY KEY,
    hospital_id VARCHAR(36) NOT NULL,
    ward_id VARCHAR(36),
    bed_number VARCHAR(50),
    medical_team_id VARCHAR(36),
    admitting_consultant_id VARCHAR(36),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    hospital_number VARCHAR(50) NOT NULL UNIQUE,
    admission_date DATETIME NOT NULL,
    admission_type VARCHAR(50) NOT NULL,
    primary_diagnosis TEXT,
    specialty_required VARCHAR(255),
    acuity_level VARCHAR(50) NOT NULL DEFAULT 'LOW',
    news_score INT NOT NULL DEFAULT 0,
    is_discharge_ready TINYINT(1) NOT NULL DEFAULT 0,
    estimated_discharge_date DATE,
    status VARCHAR(50) NOT NULL DEFAULT 'ADMITTED',
    created_at DATETIME NOT NULL,
    updated_at DATETIME,
    CONSTRAINT fk_patient_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    CONSTRAINT fk_patient_ward FOREIGN KEY (ward_id) REFERENCES wards(id),
    CONSTRAINT fk_patient_team FOREIGN KEY (medical_team_id) REFERENCES medical_teams(id),
    CONSTRAINT fk_patient_consultant FOREIGN KEY (admitting_consultant_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
