CREATE TABLE patient (
    id                      VARCHAR(36)  NOT NULL PRIMARY KEY,
    hospital_id             VARCHAR(36)  NOT NULL,
    ward_id                 VARCHAR(36)  NOT NULL,
    bed_number              VARCHAR(20)  NULL,
    medical_team_id         VARCHAR(36)  NOT NULL,
    admitting_consultant_id VARCHAR(36)  NULL,
    first_name              VARCHAR(100) NOT NULL,
    last_name               VARCHAR(100) NOT NULL,
    date_of_birth           DATE         NOT NULL,
    gender                  VARCHAR(20)  NULL,
    hospital_number         VARCHAR(50)  NOT NULL,
    admission_date          DATETIME     NOT NULL,
    admission_type          VARCHAR(20)  NOT NULL,
    primary_diagnosis       TEXT         NULL,
    specialty_required      VARCHAR(100) NULL,
    acuity_level            VARCHAR(10)  NOT NULL DEFAULT 'LOW',
    news_score              INT          NOT NULL DEFAULT 0,
    is_discharge_ready      BOOLEAN      NOT NULL DEFAULT FALSE,
    estimated_discharge_date DATE        NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ADMITTED',
    created_at              DATETIME     NOT NULL,
    updated_at              DATETIME     NOT NULL,
    UNIQUE KEY uq_patient_hospital_number (hospital_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
