CREATE TABLE rounds (
    id VARCHAR(36) PRIMARY KEY,
    hospital_id VARCHAR(36) NOT NULL,
    ward_id VARCHAR(36) NOT NULL,
    medical_team_id VARCHAR(36) NOT NULL,
    shift_id VARCHAR(36),
    round_type VARCHAR(50) NOT NULL,
    lead_doctor_id VARCHAR(36),
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    scheduled_time DATETIME,
    started_at DATETIME,
    completed_at DATETIME,
    team_members TEXT,
    created_at DATETIME NOT NULL,
    CONSTRAINT fk_round_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    CONSTRAINT fk_round_ward FOREIGN KEY (ward_id) REFERENCES wards(id),
    CONSTRAINT fk_round_team FOREIGN KEY (medical_team_id) REFERENCES medical_teams(id),
    CONSTRAINT fk_round_shift FOREIGN KEY (shift_id) REFERENCES shifts(id),
    CONSTRAINT fk_round_lead FOREIGN KEY (lead_doctor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE patient_round_reviews (
    id VARCHAR(36) PRIMARY KEY,
    hospital_id VARCHAR(36) NOT NULL,
    round_id VARCHAR(36) NOT NULL,
    patient_id VARCHAR(36) NOT NULL,
    reviewed_by_id VARCHAR(36) NOT NULL,
    review_order INT NOT NULL,
    news_score_at_review INT NOT NULL,
    clinical_status VARCHAR(50) NOT NULL,
    was_examined TINYINT(1) NOT NULL DEFAULT 1,
    management_plan TEXT,
    discharge_assessment VARCHAR(50) NOT NULL DEFAULT 'NONE',
    notified_next_of_kin TINYINT(1) NOT NULL DEFAULT 0,
    reviewed_at DATETIME NOT NULL,
    UNIQUE KEY uk_round_patient (round_id, patient_id),
    CONSTRAINT fk_prr_hospital FOREIGN KEY (hospital_id) REFERENCES hospitals(id),
    CONSTRAINT fk_prr_round FOREIGN KEY (round_id) REFERENCES rounds(id),
    CONSTRAINT fk_prr_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_prr_reviewer FOREIGN KEY (reviewed_by_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
