global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: careround-core
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['careround-core:8080']

  - job_name: careround-notification
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['careround-notification:8081']

  - job_name: careround-audit
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['careround-audit:8082']

  # local dev only — remove in production
  - job_name: careround-core-local
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  # local dev only — remove in production
  - job_name: careround-notification-local
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']

  # local dev only — remove in production
  - job_name: careround-audit-local
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8082']
